language: scala
scala:
   - 2.11.7
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - torsten.scholak@googlemail.com
script: "sbt clean coverage test"
after_success: "sbt coveralls"
